"""Render the combined Agent Acceptance Report as markdown."""

from __future__ import annotations

from .models import CombinedReport


_VERDICT_LINE = {
    "PASS": "**ACCEPTED** — agent passes behavioral sign-off AND memory-governance gate.",
    "FAIL": "**REJECTED** — at least one gate failed. Do not hand off.",
    "BEHAVIORAL_ONLY": "**CONDITIONAL** — behavioral sign-off passed; memory governance not assessed.",
}


def _fmt(x: float | None) -> str:
    return f"{x:.3f}" if x is not None else "—"


def _behavioral_table(report: CombinedReport) -> str:
    b = report.behavioral
    if not b.ran:
        return f"_Not run: {b.error}_"
    if not b.scenarios:
        return "_No scenarios._"
    rows = ["| Scenario | Verdict |", "| --- | --- |"]
    for s in b.scenarios:
        rows.append(f"| {s.get('name','')} | {'PASS' if s.get('passed') else 'FAIL'} |")
    return "\n".join(rows)


def _memory_block(report: CombinedReport) -> str:
    m = report.memory
    if not m.ran:
        return f"_Not assessed: {m.error}_"
    return (
        "| Metric | Value |\n| --- | --- |\n"
        f"| MGS (U·(1−A)·(1−F)) | {_fmt(m.mgs)} |\n"
        f"| Utility (U) | {_fmt(m.utility)} |\n"
        f"| Access-leak rate (A, lower better) | {_fmt(m.access_control)} |\n"
        f"| Forgetting-failure rate (F, lower better) | {_fmt(m.active_forgetting)} |\n"
        f"| Checkpoints scored | {m.n_checkpoints} |\n"
        f"| Governance threshold | {report.memory_threshold:.2f} |"
    )


def render_report(report: CombinedReport) -> str:
    verdict = report.verdict.value
    line = _VERDICT_LINE.get(verdict, verdict)
    return f"""# Agent Acceptance Report — {report.project}

**Overall verdict:** {verdict}

{line}

## 1. Behavioral sign-off (cross-layer: prompt / tool / memory / retrieval)

{_behavioral_table(report)}

## 2. Memory governance (GateMem-aligned MGS)

{_memory_block(report)}

---
Generated by `agent-acceptance` — combining [agent-handoff](https://github.com/mastroke/agent-handoff) and [verified-memory-gate](https://github.com/mastroke/verified-memory-gate).
"""
